### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by leonovk** [vscodethemes/web#266]
Give a thumbs up or a heart if you want Ruby to be added to the site.

**Comment by SethBashamDev** [comment]
Just came here to as this as well. Its something small, but it would help me pick a theme better.

**Comment by jschr** [comment]
I'd love to add Ruby to the website. It's been a long time since I've used Ruby so if someone would like to suggest the code preview I'll add it to the site. 

The code should:
- Be exactly 14 lines including empty lines (so that the font sizes remain the same across different languages)
- Be valid syntax and ideally a working program
- Include a comment

**Comment by leonovk** [comment]
@jschr I suggest this code. It has exactly 14 lines.
```ruby
class Calculator
  SOME_CONST = 'string'.freeze

  attr_accessor :operations

  def initialize(operations = [])
    @operations = operations
  end

  # A comment
  def calculate
    operations.each { |operation| puts operation.call }
  end
end
```

**Comment by jschr** [comment]
Ruby as been added to the site. Thanks for the code snipper @leonovk
